export const LOCAL_STORAGE_PROMPT_KEY = "LOCAL_STORAGE_PROMPT_KEY";
export const LOCAL_STORAGE_PROMPT_INFO = "LOCAL_STORAGE_PROMPT_INFO";
export const LOCAL_STORAGE_PROMPT_CURRENT = "LOCAL_STORAGE_PROMPT_CURRENT";
